# .github/release.yml

changelog:
  categories:
    - title: New Features 
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: 👒 Dependencies
      labels:
        - dependencies
