name: Notion Release Page

on:
  release:
    types:
      - created


jobs:
    use_api:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: 3.2.2

        - name: Install Dependencies
          run: |
            gem install bundler
            bundle install

        - name: Query GitHub REST API
          id: get-release
          run: |
            github_api_url="https://api.github.com/repos/internal-product-changelog/changelog/releases/latest"

            github_headers="Accept: application/vnd.github+json
                            X-GitHub-Api-Version: 2022-11-28"
            github_response=$(curl -sS --http1.1 -H "$github_headers" $github_api_url)
            
            echo "Raw GitHub API Response:"
            echo "$github_response"            

        - name: Run Ruby Script
          run: |
            # Access individual environment variables
            release_name="${RELEASE_NAME}"
            release_tag="${RELEASE_TAG}"
            release_description="${RELEASE_DESCRIPTION}"
            release_created_at="${RELEASE_CREATED_AT}"

            echo "Release Name: $release_name"
            echo "Release Tag: $release_tag"
            echo "Release Description: $release_description"
            echo "Release Created At: $release_created_at"

            ruby .github/scripts/create-release-notion-document.rb "$release_info"