name: Notion Release Page

on:
  release:
    types:
      - created


jobs:
  create-release-notion-document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Query GitHub GraphQL API
        id: get-release
        run: |
          github_api_url="https://api.github.com/graphql"
          query=$(cat <<'GRAPHQL'
            query {
              repository(owner: "internal-product-changelog", name: "changelog") {
                releases(last: 1) {
                  nodes {
                    name
                    tagName
                    description
                    createdAt
                  }
                }
              }
            }
          GRAPHQL
          )

          github_token="${{ secrets.GITHUB_TOKEN }}"

          github_headers="Authorization: Bearer $github_token"
          github_response=$(curl -sS --http1.1 -X POST -H "$github_headers" -d "{\"query\":\"$query\"}" $github_api_url)
          
          echo "::set-output name=release_info::$github_response"

      - name: Run Ruby Script
        run: |
          release_info=$(echo "${{ steps.get-release.outputs.release_info }}")

          echo "Raw Release Info:"
          echo "$release_info"

          ruby .github/scripts/create-release-notion-document.rb "$release_info"