name: Notion Release Page

on:
  release:
    types:
      - created


jobs:
  create-release-notion-document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Fetch GitHub Release Text
        run: |
          github_api_url="https://api.github.com/graphql"
          query=$(cat <<'GRAPHQL'
            query {
              repository(owner: "internal-product-changelog", name: "changelog") {
                releases(last: 1) {
                  nodes {
                    body
                  }
                }
              }
            }
          GRAPHQL
          )

          github_token="${{ secrets.GITHUB_TOKEN }}"

          github_headers="Authorization: Bearer $github_token
          Content-Type: application/json
          Accept: application/json"

          github_response=$(curl -sS -X POST -H "$github_headers" -d "{\"query\":\"$query\"}" $github_api_url)
          release_text=$(ruby -e 'require "json"; data = JSON.parse(STDIN.read); puts data["data"]["repository"]["releases"]["nodes"][0]["body"]' <<< "$github_response")

          echo "::set-output name=release_text::$release_text"
      - name: Run Script
        run: ruby .github/scripts/create-release-notion-document.rb ${{ env.release_text }}
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}