name: Notion Release Page

on:
  release:
    types:
      - created


jobs:
  create-release-notion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Query GitHub GraphQL API
        id: get-release
        run: |
          github_api_url="https://api.github.com/graphql"
          query=$(cat <<'GRAPHQL'
            query {
              repository(owner: "internal-product-changelog", name: "changelog") {
                releases(last: 1) {
                  nodes {
                    name
                    tagName
                    description
                    createdAt
                  }
                }
              }
            }
          GRAPHQL
          )

          github_token="${{ secrets.GITHUB_TOKEN }}"

          github_headers="Authorization: Bearer $github_token"
          github_response=$(curl -sS --http1.1 -X POST -H "$github_headers" -d "{\"query\":\"$query\"}" $github_api_url)
          
          # Extract individual fields from the JSON response
          release_name=$(echo "$github_response" | jq -r '.data.repository.releases.nodes[0].name')
          release_tag=$(echo "$github_response" | jq -r '.data.repository.releases.nodes[0].tagName')
          release_description=$(echo "$github_response" | jq -r '.data.repository.releases.nodes[0].description')
          release_created_at=$(echo "$github_response" | jq -r '.data.repository.releases.nodes[0].createdAt')

          # Set individual environment variables
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV
          echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV
          echo "RELEASE_DESCRIPTION=$release_description" >> $GITHUB_ENV
          echo "RELEASE_CREATED_AT=$release_created_at" >> $GITHUB_ENV

      - name: Run Ruby Script
        run: |
          # Access individual environment variables
          release_name="${RELEASE_NAME}"
          release_tag="${RELEASE_TAG}"
          release_description="${RELEASE_DESCRIPTION}"
          release_created_at="${RELEASE_CREATED_AT}"

          echo "Release Name: $release_name"
          echo "Release Tag: $release_tag"
          echo "Release Description: $release_description"
          echo "Release Created At: $release_created_at"

          ruby .github/scripts/create-release-notion-document.rb "$release_info"